### ISSUE TITLE
Failed to open thrift connection to Cassandra at 127.0.0.1:9160

### ISSUE THREAD

**Issue by vladikoff** [koeninger/spark-cassandra-example#1]
Hey! Following the example in the README I get the stack below on OS X, am I missing something in the configuration?

```
Exception in thread "main" java.io.IOException: Failed to open thrift connection to Cassandra at 127.0.0.1:9160
    at com.datastax.spark.connector.cql.CassandraConnector.createThriftClient(CassandraConnector.scala:132)
    at com.datastax.spark.connector.cql.CassandraConnector.createThriftClient(CassandraConnector.scala:138)
    at com.datastax.spark.connector.cql.CassandraConnector.withCassandraClientDo(CassandraConnector.scala:144)
    at com.datastax.spark.connector.rdd.partitioner.CassandraRDDPartitioner.partitions(CassandraRDDPartitioner.scala:144)
    at com.datastax.spark.connector.rdd.CassandraRDD.getPartitions(CassandraRDD.scala:290)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:219)
    at org.apache.spark.rdd.RDD$$anonfun$partitions$2.apply(RDD.scala:217)
    at scala.Option.getOrElse(Option.scala:120)
    at org.apache.spark.rdd.RDD.partitions(RDD.scala:217)
    at org.apache.spark.rdd.RDD$$anonfun$take$1.apply(RDD.scala:1255)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
    at org.apache.spark.rdd.RDD.withScope(RDD.scala:286)
    at org.apache.spark.rdd.RDD.take(RDD.scala:1250)
    at org.apache.spark.rdd.RDD$$anonfun$first$1.apply(RDD.scala:1290)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:147)
    at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:108)
    at org.apache.spark.rdd.RDD.withScope(RDD.scala:286)
    at org.apache.spark.rdd.RDD.first(RDD.scala:1289)
    at org.koeninger.HelloWorldExample$.main(HelloWorldExample.scala:18)
    at org.koeninger.HelloWorldExample.main(HelloWorldExample.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.apache.spark.deploy.SparkSubmit$.org$apache$spark$deploy$SparkSubmit$$runMain(SparkSubmit.scala:665)
    at org.apache.spark.deploy.SparkSubmit$.doRunMain$1(SparkSubmit.scala:170)
    at org.apache.spark.deploy.SparkSubmit$.submit(SparkSubmit.scala:193)
    at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:112)
    at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
Caused by: org.apache.thrift.transport.TTransportException: java.net.ConnectException: Connection refused
    at org.apache.thrift.transport.TSocket.open(TSocket.java:185)
    at org.apache.thrift.transport.TFramedTransport.open(TFramedTransport.java:81)
    at org.apache.cassandra.thrift.TFramedTransportFactory.openTransport(TFramedTransportFactory.java:41)
    at com.datastax.spark.connector.cql.DefaultConnectionFactory$.createThriftClient(CassandraConnectionFactory.scala:45)
    at com.datastax.spark.connector.cql.CassandraConnector.createThriftClient(CassandraConnector.scala:127)
    ... 29 more
Caused by: java.net.ConnectException: Connection refused
    at java.net.PlainSocketImpl.socketConnect(Native Method)
    at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:345)
    at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
    at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
    at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
    at java.net.Socket.connect(Socket.java:589)
    at org.apache.thrift.transport.TSocket.open(TSocket.java:180)
    ... 33 more
15/09/16 14:16:38 INFO CassandraConnector: Disconnected from Cassand
```

**Comment by koeninger** [comment]
Looks like cassandra isn't listening on that address / port.

I'd make sure cassandra is running and that it's accepting connections before even trying to run the spark example.  Should be able to verify with telnet or lsof

**Comment by vladikoff** [comment]
@koeninger Thank you for the quick response, Seems like it could be compat between different versions. 
On OS X `brew` installed Cassandra 2.2.0 and Spark 1.4.1.

Seems like we use Spark 1.2 in prod so I need to downgrade my local system to Cassandra 2.1 and change 

```
 libraryDependencies ++= Seq(
        "com.datastax.spark" %% "spark-cassandra-connector" % "1.1.0-alpha3",
        // spark will already be on classpath when using spark-submit.
        // marked as provided, so that it isn't included in assembly.
        "org.apache.spark" %% "spark-catalyst" % "1.1.0" % "provided",
        "org.scalatest" %% "scalatest" % "2.1.5" % "test"
      )
```

 to support connector 1.2, looking at https://github.com/datastax/spark-cassandra-connector#version-compatibility

**Comment by vladikoff** [comment]
So for some reason the default Cassandra comes with `start_rpc: false`. The key to fix this issue: 

Install Cassandra using these instructions http://www.datastax.com/2012/01/working-with-apache-cassandra-on-mac-os-x instead of `brew`. Find `start_rpc: false` in `cassandra.yaml` and change it to `true`

**Comment by abhidemon** [comment]
Thanks vladikoff , This one solves my problem too. I was getting the same exception earlier.

But i didn't have to reinstall cassandra all over again. I just changed the value of `start_rpc` in cassandra.yaml from false to `start_rpc: true` and restarted cassandra. 

NOTE: 
I am using spark 1.1.0 with cassandra 2.2.3. I feared will have to downgrade cassandra which i didnt want to and actually didn't have to either. 

Thank you :)

**Comment by Lceeba** [comment]
It still does not work for me. Unable to launch SparkContext on the RPC port.

get this error for CQLSH

cassandra:/opt/cassandra/bin $ cqlsh 10.226.68.252 9160

## Connection error: ('Unable to connect to any servers', {'10.226.68.252': error(111, "Tried connecting to [('10.226.68.252', 9160)]. Last error: Connection refused")})

SparkContext Error:

cassandra:/opt/cassandra/resources/cassandra/conf $ dse spark
Exception in thread "main" java.io.IOException: Failed to open thrift connection to Cassandra at 10.226.68.252:9160
        at com.datastax.bdp.spark.cassandra.ThriftConnectionUtil$.createThriftClient(ThriftConnectionUtil.scala:48)

## 

Lokesh

**Comment by Lceeba** [comment]
## Under cassandra.yaml file:

In cassandra.yaml file :

start_rpc: true

rpc_address: 10.226.68.252

# rpc_interface: eth1

# rpc_interface_prefer_ipv6: false

# port for Thrift to listen for clients on

rpc_port: 9160

# RPC address to broadcast to drivers and other Cassandra nodes. This cannot

# be set to 0.0.0.0. If left blank, this will be set to the value of

# rpc_address. If rpc_address is set to 0.0.0.0, broadcast_rpc_address must

# be set.

# broadcast_rpc_address: 1.2.3.4

# enable or disable keepalive on rpc/native connections

rpc_keepalive: true

**Comment by koeninger** [comment]
If you can't even connect with cqlsh, its a Cassandra setup or network
problem, not a spark problem
